### ISSUE TITLE
Unable to resolve module `react-native/Libraries/Lists/VirtualizedList`

### ISSUE THREAD

**Issue by lucasleelz** [cooperka/react-native-immutable-list-view#20]
Hi,
`react-native/Libraries/Lists/VirtualizedList` Module does not exist in the module of `react-native/Libraries/Lists`。

- react v16.0.0-alpha.6
- react-native v0.43.3

**Comment by cooperka** [comment]
@lucasleelz have you run the included `download-flatlist` script? Currently you need to get the files from React Native's `master` branch in order to use them.

In RN v0.43 they're [still nested under `CustomComponents`](https://github.com/facebook/react-native/tree/0.43-stable/Libraries/CustomComponents), but they're under `Lists` on master.

**Comment by lucasleelz** [comment]
Yes, I know what you said. But I think it should depend on the stable version. Not master.

**Comment by cooperka** [comment]
I agree; it depended on master originally because there was no stable version at all, and the only way to use it was to copy the file in. Now that it's no longer experimental, I'll try to release a new version soon that uses the stable version instead of master. I'd just rather not make too many breaking changes in a row.

**Comment by cooperka** [comment]
Created new issue for this: https://github.com/cooperka/react-native-immutable-list-view/issues/22

**Comment by lucasleelz** [comment]
I am a little like you, Haha...
