### ISSUE TITLE
immutable as dev dependency

### ISSUE THREAD

**Issue by jamesholcomb** [cooperka/react-native-immutable-list-view#7]
Hi, thanks for the work on this package.

I was curious if it were possible to make immutable a `devDependency` in your package.json.  It seems react-native already specifies it, albeit an older version.

**Comment by cooperka** [comment]
Hi @jamesholcomb, thanks for the suggestion! I think that should work well. I also want to improve the peerDependencies so there are less npm warnings when using an `rc` version of React Native. I'll try to get around to both these changes soon, but in the meantime feel free to submit a PR for your suggestion.

**Comment by cooperka** [comment]
Update: I tried including `immutable` as a `peerDependency`, but React Native's version (which happens to be over a year old) has several issues. It prints loads of warnings about deprecated `iterable.length`, and their version also fails snapshot tests because of the size of the items in `ListViewDataSource`.

You can see the failing tests [here](https://travis-ci.org/cooperka/react-native-immutable-list-view/jobs/195047322) if you're interested. I'm going to have to keep it as an explicit dependency until React Native can upgrade.

Any particular reason you wanted it out of `dependencies`?

**Comment by jamesholcomb** [comment]
Nope. That makes sense.
